/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JPanel;

/**
 *
 * @author Blayder510
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }
    
    private void changePanel(JPanel jPanel){
        jPanelPrincipal.removeAll();
        jPanelPrincipal.setLayout(new java.awt.BorderLayout());
        jPanelPrincipal.add(jPanel, java.awt.BorderLayout.CENTER);
        jPanelPrincipal.revalidate();
        jPanelPrincipal.repaint();
    
        activarPanel(jPanel);
    }
    
    private void activarPanel(javax.swing.JPanel jPanel) {
        jPanelPaP.setEnabled(false);
        jPanelPaP.setVisible(false);
    
        jPanelPrd.setEnabled(false);
        jPanelPrd.setVisible(false);
    
        /*jPanelConsulta.setEnabled(false);
        jPanelConsulta.setVisible(false);

        jPanelInevntario.setEnabled(false);
        jPanelInevntario.setVisible(false);
    
        jPanelRegis_Inventario.setEnabled(false);
        jPanelRegis_Inventario.setVisible(false);*/
    
        jPanel.setVisible(true);
        jPanel.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelPaP = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelPrd = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelOrd = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MbMenu = new javax.swing.JMenu();
        MnItPaP = new javax.swing.JMenuItem();
        MbInvt = new javax.swing.JMenu();
        MnItPrd = new javax.swing.JMenuItem();
        MbVta = new javax.swing.JMenu();
        MnItOrd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrincipal.setBackground(new java.awt.Color(51, 255, 51));

        jPanelPaP.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Tienda de Pinturas Comex");

        javax.swing.GroupLayout jPanelPaPLayout = new javax.swing.GroupLayout(jPanelPaP);
        jPanelPaP.setLayout(jPanelPaPLayout);
        jPanelPaPLayout.setHorizontalGroup(
            jPanelPaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaPLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel3)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        jPanelPaPLayout.setVerticalGroup(
            jPanelPaPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaPLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addContainerGap(359, Short.MAX_VALUE))
        );

        jPanelPrd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Productos");

        javax.swing.GroupLayout jPanelPrdLayout = new javax.swing.GroupLayout(jPanelPrd);
        jPanelPrd.setLayout(jPanelPrdLayout);
        jPanelPrdLayout.setHorizontalGroup(
            jPanelPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrdLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel2)
                .addContainerGap(491, Short.MAX_VALUE))
        );
        jPanelPrdLayout.setVerticalGroup(
            jPanelPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrdLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addContainerGap(352, Short.MAX_VALUE))
        );

        jPanelOrd.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Orden de Venta");

        javax.swing.GroupLayout jPanelOrdLayout = new javax.swing.GroupLayout(jPanelOrd);
        jPanelOrd.setLayout(jPanelOrdLayout);
        jPanelOrdLayout.setHorizontalGroup(
            jPanelOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        jPanelOrdLayout.setVerticalGroup(
            jPanelOrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOrdLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPaP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelPrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanelOrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MbMenu.setText("Menu");
        MbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbMenuActionPerformed(evt);
            }
        });

        MnItPaP.setText("Pagina Principal");
        MnItPaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItPaPActionPerformed(evt);
            }
        });
        MbMenu.add(MnItPaP);

        jMenuBar1.add(MbMenu);

        MbInvt.setText("Inventario");

        MnItPrd.setText("Productos");
        MnItPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItPrdActionPerformed(evt);
            }
        });
        MbInvt.add(MnItPrd);

        jMenuBar1.add(MbInvt);

        MbVta.setText("Venta");

        MnItOrd.setText("Orden de Pago");
        MnItOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItOrdActionPerformed(evt);
            }
        });
        MbVta.add(MnItOrd);

        jMenuBar1.add(MbVta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MnItPaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItPaPActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "Pagina principal");
        changePanel(jPanelPaP);
    }//GEN-LAST:event_MnItPaPActionPerformed

    private void MbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MbMenuActionPerformed

    private void MnItPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItPrdActionPerformed
        // TODO add your handling code here:
        changePanel(jPanelPrd);
    }//GEN-LAST:event_MnItPrdActionPerformed

    private void MnItOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItOrdActionPerformed
        // TODO add your handling code here:
        changePanel(jPanelOrd);
    }//GEN-LAST:event_MnItOrdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MbInvt;
    private javax.swing.JMenu MbMenu;
    private javax.swing.JMenu MbVta;
    private javax.swing.JMenuItem MnItOrd;
    private javax.swing.JMenuItem MnItPaP;
    private javax.swing.JMenuItem MnItPrd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelOrd;
    private javax.swing.JPanel jPanelPaP;
    private javax.swing.JPanel jPanelPrd;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
